alias battery='echo "import os;battery_full=float(os.popen(\"cat /sys/class/power_supply/BAT1/energy_full\").read());battery_currently=float(os.popen(\"cat /sys/class/power_supply/BAT1/energy_now\").read());battery_percentage=float((battery_currently/battery_full)*100);print \"battery percentage: \" + str(battery_percentage)" | python'
alias ddg=' links2 duckduckgo.com/?kp=-1 '
alias google=' links2 google.com '
alias install=' apt-get install -y -q '
alias make-executable=' chmod 777 '
alias mv='mv -v '
alias nano=' nano -$ '
alias password-gen="openssl rand -base64 4096 | openssl dgst -sha256 | sed \"s/(stdin)= //g\""
alias remove=' apt-get remove -y -q '
alias rm=' rm -r -f -v '
alias save-aliases='alias -p > ~/.bash_aliases && echo "all aliases have been saved to ~/.bash_aliases"'
alias backup-aliases='alias -p > ~/.bash_aliases && echo "all aliases have been saved to ~/.bash_aliases"'
alias restart-openvpn='`cat .bashrc | grep openvpn | grep nohup`'
alias screen-off='vbetool dpms off'
alias screen-on='vbetool dpms on'
alias search=' apt-get update -y -q ; apt-cache search '
alias srm=' srm -vzrf ' 
alias ssh-restart=' service ssh stop && sleep 2 && service ssh start '
alias torrent=' transmission-cli -er '
alias update=' apt-get update -y -q && apt-get autoremove -y && apt-get autoclean -y '
alias wifi-ipad="echo \"ZWNobyAnaW1wb3J0IG9zO3ByaW50KCJJdCBhcHBlYXJzIHRoYXQgeW91IGFyZSBjb25uZWN0ZWQgdG8gdGhlIGlQYWQuIiBpZiAiMTcyLjIwLjEwIiBpbiBvcy5wb3BlbigiaWZjb25maWciKSBlbHNlICJJdCBhcHBlYXJzIHRoYXQgeW91IGFyZSBub3QgY29ubmVjdGVkIHRvIHRoZSBpUGFkcyB3aWZpLiIpJyB8IHB5dGhvbg==\" | base64 --decode | bash"
alias wifi-restart='ifconfig wlan0 down && sleep 2 && ifconfig wlan0 up'
alias wifi-scan='iwlist eth0 scan'
